type IU = "Iue";
type Upper = Uppercase<IU>;
// type Upper = "IUE"
type Lower = Lowercase<IU>;
// type Lower = "iue"
type Capital = Capitalize<IU>;
// type Capital = "Iue"
type UnCapital = Uncapitalize<IU>;
// type UnCapital = "iue"
